# Generated by Django 6.0.7 on 2026-07-29 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_workspace_fk'),
        ('workspace', '0002_remove_workspacemember_unique_workspace_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_name_per_workspace',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_workspa_6f3405_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='project_mem_project_0d0b7d_idx',
            old_name='project_mem_project_797e6f_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='projects_workspa_658984_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_project_name_per_workspace'),
        ),
    ]
