# Generated by Django 6.0.7 on 2026-07-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_unique_project_name_per_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wip_limit_enabled', models.BooleanField(default=False)),
                ('default_column_wip_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban', to='project.project')),
            ],
            options={
                'db_table': 'kanban',
            },
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_duration_weeks', models.PositiveSmallIntegerField(default=2)),
                ('definition_of_done', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrum', to='project.project')),
            ],
            options={
                'db_table': 'scrum',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='project.scrum')),
            ],
            options={
                'db_table': 'sprints',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='scrum',
            name='current_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.sprint'),
        ),
        migrations.CreateModel(
            name='SprintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('planning', 'Planning'), ('daily_standup', 'Daily Standup'), ('review', 'Review'), ('retrospective', 'Retrospective'), ('backlog_refinement', 'Backlog Refinement')], max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='project.sprint')),
            ],
            options={
                'db_table': 'sprint_events',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['scrum', 'status'], name='sprints_scrum_i_503ca9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('scrum', 'name'), name='unique_sprint_name_per_scrum'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='sprint_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='sprintevent',
            index=models.Index(fields=['sprint', 'type'], name='sprint_even_sprint__f8fda8_idx'),
        ),
    ]
