# Generated by Django 6.0.7 on 2026-08-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_kanban_scrum_sprint_scrum_current_sprint_sprintevent_and_more'),
        ('workspace', '0002_remove_workspacemember_unique_workspace_owner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='unique_project_member',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='workspace_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='workspace.workspacemember'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'workspace_member'), name='unique_project_member'),
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='user',
        ),
    ]
