# Generated by Django 6.0.7 on 2026-07-31 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_kanban_scrum_sprint_scrum_current_sprint_sprintevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='project.project')),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('column_type', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('wip_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='board.board')),
            ],
            options={
                'db_table': 'board_columns',
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('board', 'position'), name='unique_board_column_position'), models.UniqueConstraint(fields=('board', 'name'), name='unique_board_column_name'), models.CheckConstraint(condition=models.Q(('wip_limit__isnull', True), ('wip_limit__gt', 0), _connector='OR'), name='board_column_wip_limit_positive')],
            },
        ),
    ]
